apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    kube-monkey/enabled: "{{ .Values.kubemonkey.enable }}"
    kube-monkey/identifier: {{ template "helm.name" . }}
    kube-monkey/mtbf: "{{ .Values.kubemonkey.mtbf }}"
    kube-monkey/kill-mode: "{{ .Values.kubemonkey.killmode }}"
    kube-monkey/kill-value: "{{ .Values.kubemonkey.killvalue }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "helm.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "helm.name" . }}
        release: {{ .Release.Name }}
        kube-monkey/enabled: "{{ .Values.kubemonkey.enable }}"
        kube-monkey/identifier: {{ template "helm.name" . }}
        kube-monkey/mtbf: "{{ .Values.kubemonkey.mtbf }}"
        kube-monkey/kill-mode: "{{ .Values.kubemonkey.killmode }}"
        kube-monkey/kill-value: "{{ .Values.kubemonkey.killvalue }}"
    spec:
      containers:
      - name: api
        image: "vfarcic/go-demo-5:{{ .Values.image.tag }}"
        env:
        - name: DB
          value: {{ template "helm.fullname" . }}-db
        readinessProbe:
          httpGet:
            path: /demo/hello?health=true
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /demo/hello?health=true
            port: 8080
        resources:
{{ toYaml .Values.resources | indent 10 }}
